spring.application.name=TaskHub

# ??????? (???????????? MYSQL_DATABASE ??)
spring.datasource.url=jdbc:mysql://localhost:3307/taskhub_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=my_root_pw

# ???? Java Entity ???????? (????????)
spring.jpa.hibernate.ddl-auto=update
# ????????? SQL ??
spring.jpa.show-sql=true